name: FruitBosses
version: '1.0-SNAPSHOT'
main: byrnes.jonathan.FruitBosses
api-version: '1.21'
softdepend: [MythicMobs]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true